### ISSUE TITLE
resume and progress bar

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#15]
Check login details of session ID 496 and 495. I think they are same. I did not get resume option. Also resume option did not take previous score, progress, or resume slide.

I think if u just complete the pre-test and post-test, it is showing training completed as 1. check session ID 495 with progress .37. I that session I just completed pre-test and post-test and few questions. Training completed will be one only if progress is 100%.

**Comment by prabodhpanindre** [comment]
If you complete entire module, then resume option should not come

**Comment by waqidvolli** [comment]
Previously:

If user completes post-test (end of module), then training is marked as completed =1. 
And we use training_completed to show resume OR not.

Progress has been recently introduced.

So you want to change the logic to below?
Training completed only when progress =100%?

But with current flow it wont make sense because, once user has completed the post-test, irrespective of if he has completed it 100% or not, he will not be able to visit any previous slide as there is no option to do so. So resume will always take to thank you slide.

We need to discuss this.
